#!/bin/sh

_basename() {
    guile --no-auto-compile -L ${GUILE_PREFIX}/share/guile/site/2.0 -L ${REPO}/sources/gash -L ${REPO}/sources/gash-core-utils -L ${REPO}/sources/gash-assets/modules -e main -s ${REPO}/sources/gash-assets/basename.scm $1
}

guile --no-auto-compile -L ${GUILE_PREFIX}/share/guile/site/2.0 -L ${REPO}/sources/gash -L ${REPO}/sources/gash-core-utils -L ${REPO}/sources/gash-assets/modules -e main -s ${REPO}/sources/gash-assets/\[.scm "$@"
