#! /bin/sh

# GNU Mes --- Maxwell Equations of Software
# Copyright © 2018,2019 Jan (janneke) Nieuwenhuizen <janneke@gnu.org>
#
# This file is part of GNU Mes.
#
# GNU Mes is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or (at
# your option) any later version.
#
# GNU Mes is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with GNU Mes.  If not, see <http://www.gnu.org/licenses/>.

if [ "$V" = 2 ]; then
    set -x
fi

export bindir=${REPO}/sources/mes/scripts
export SCHEME=guile
export MES_PREFIX=${REPO}/sources/mes

export HEX2=${REPO}/staging/bin/hex2
export M1=${REPO}/staging/bin/M1
export BLOOD_ELF=${REPO}/staging/bin/blood-elf

export SCHEME=mes
export MES_ARENA=20000000
export MES_MAX_ARENA=${MES_ARENA}
export MES_STACK=5000000

GUILE_LOAD_PATH=${REPO}/sources/mes-assets/modules
export GUILE_LOAD_PATH

if [ ! -f $bindir/mescc.scm ]; then
   bindir=$(dirname $0)
fi

sep=
if [ "$(basename ${SCHEME-$MES})" = "mes" ]; then
    sep=--
fi

${SCHEME-$MES} \
    --no-auto-compile\
    -e main\
    -L ${REPO}/sources/mes-assets/modules\
    $bindir/mescc.scm\
    $sep\
    "$@"
